web/app/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

from apps import customer

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
    url(r'^accounts/', include('apps.customer.urls', namespace='customer')),
    url(r'^organisation/', include('apps.organisation.urls', namespace='organisation')),
    url(r'^', include('cms.urls')),
)


# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

web/apps/organisation/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from apps.organisation.views import CreateOrganisationView, serve_qr_code_image, CreateLoginView, LoginInfoView, \
    LoginDisallowView, LoginAllowView, EditOrganisationView

urlpatterns = [
    url(r'^$', login_required(CreateOrganisationView.as_view()), name='organisation-index'),
    url(r'^edit/(?P<id>\w[-\w]*)/$', EditOrganisationView.as_view(), name='organisation-edit-item'),
    url(r'^qr/$', serve_qr_code_image, name='serve_qr_code_image'),
    url(r'^create_login/$', CreateLoginView.as_view(), name='create_login'),
    url(r'^login/info/$', LoginInfoView.as_view(), name='login_info'),
    url(r'^login/allow/$', csrf_exempt(LoginAllowView.as_view()), name='login_allow'),
    url(r'^login/disallow/$', csrf_exempt(LoginDisallowView.as_view()), name='login_disallow'),
    # url(r'^change-password/$',
    #     login_required(self.change_password_view.as_view()),
    #     name='change-password'),
]

web/app/templates/base.html
{% load cms_tags menu_tags sekizai_tags %}
{% load render_bundle from webpack_loader %}
<!doctype html>
<html>
    <head>
        <title>{% block title %}This is my new project home page{% endblock title %}</title>
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

        {% render_bundle 'main' 'css' %}
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
        {% render_block "css" %}
    </head>
    <body>
        {% cms_toolbar %}
        {% block header %}{% endblock header %}
        {% block content %}{% endblock content %}
        {% block footer %}{% endblock footer %}
        {% block other %}{% endblock other %}
        {% render_block "js" %}
        {% render_bundle 'main' 'js' %}
    </body>
</html>

web/app/templates/dashboard_base.html
{% load cms_tags menu_tags sekizai_tags %}
{% load render_bundle from webpack_loader %}
<!doctype html>
<html>
    <head>
        <title>{% block title %}This is my new project home page{% endblock title %}</title>
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

        {% render_bundle 'main' 'css' %}
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
        {% render_block "css" %}
    </head>
    <body>
        {% cms_toolbar %}
        <div class="layout-dashboard" data-layout-dashboard>
            <div class="layout-dashboard__header">
                <div class="layout-dashboard__header-container">
                    <div class="layout-dashboard__header-logo">
                        Logo
                    </div>
                    <div class="layout-dashboard__header-title">
                        
                    </div>
                    <div class="layout-dashboard__header-user">
                        <div class="layout-dashboard__header-user-name">
                             {{ user.email }}
                        </div>
                        <div class="layout-dashboard__header-user-image" style="background-image: url('https://www.placehold.it/100x100')">
                        </div>
                    </div>
                </div>
            </div>
            <div class="layout-dashboard__header-mobile">
                <div class="layout-dashboard__header-mobile-userimage" style="background-image: url('https://www.placehold.it/100x100')">
                </div>
                <div class="layout-dashboard__header-mobile-group">
                    <div class="layout-dashboard__header-mobile-group-pagetitle">
                     
                    </div>
                    <div class="layout-dashboard__header-mobile-group-username">
                        {{ user.email }}
                    </div>
                </div>
                <div class="layout-dashboard__header-mobile-burger" data-layout-dashboard-child="sidebarOpen">
                    <div class="icon icon-burger"></div>
                </div>
            </div>

            <div class="layout-dashboard__sidebar" data-layout-dashboard-child="sidebar">
                <div class="layout-dashboard__sidebar-overlay" data-layout-dashboard-child="sidebarClose"></div>
                <div class="layout-dashboard__sidebar-menu">
                    <a class="layout-dashboard__sidebar-menu-item {% if request.resolver_match.url_name == 'index' %}layout-dashboard__sidebar-menu-item_active{% endif %}" href="/dashboard">
                        <span class="layout-dashboard__sidebar-menu-item-text">
                            Dashboard
                        </span>
                    </a>

                    <a class="layout-dashboard__sidebar-menu-item {% if request.resolver_match.url_name == 'organisation-index' %}layout-dashboard__sidebar-menu-item_active{% endif %}" href="{% url 'organisation:organisation-index' %}">
                        <span class="layout-dashboard__sidebar-menu-item-text">
                            Organisations
                        </span>
                    </a>

                    <a class="layout-dashboard__sidebar-menu-item" href="/accounts/logout">
                        <span class="layout-dashboard__sidebar-menu-item-text">
                            Sign out
                        </span>
                    </a>
                </div>
                <div class="layout-dashboard__sidebar-close" data-layout-dashboard-child="sidebarClose">
                    <div class="icon icon-close"></div>
                </div>
            </div>
            <div class="layout-dashboard__content">
                {% block content %}{% endblock content %}
            </div>
        </div>
        {% render_block "js" %}
        {% render_bundle 'main' 'js' %}
    </body>
</html>

web/app/templates/fullwidth.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
	{% placeholder "content" %}
{% endblock content %}

web/app/templates/sidebar_left.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    <div class="sidebar">
        {% placeholder "sidebar" %}
    </div>
    <div class="content">
        {% placeholder "content" %}
    </div>
{% endblock content %}

web/app/templates/sidebar_right.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    <div class="content">
        {% placeholder "content" %}
    </div>
    <div class="sidebar">
        {% placeholder "sidebar" %}
    </div>
{% endblock content %}